stages:
  - deploy development
  - deploy production database
  - deploy production
deploy development:
  stage: deploy development
  only:
    - develop
  tags:
    - development
  variables:
    DOCKER_IMAGE_NAME: avatarnice/api-chat-x-dev
    DOCKER_IMAGE_TAG: ${CI_BUILD_TOKEN}
    DOCKER_CONTAINER_NAME: api-chat-x-container-dev
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    RABBITMQ_USER: ${RABBITMQ_USER}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  before_script:
    -  docker login -u ${DOCKER_HUB_REGISTRY_USER} -p ${DOCKER_HUB_REGISTRY_PASSWORD}
  script:
    - chmod u+x ./deploy/develop/build.sh
    - ./deploy/develop/build.sh
    - docker push avatarnice/api-chat-x-dev:${CI_BUILD_TOKEN}
    - chmod u+x ./deploy/develop/run.sh
    - ./deploy/develop/run.sh

deploy production database:
  stage: deploy production database
  only:
    - master
  tags:
    - production-db
  variables:
    DOCKER_IMAGE_NAME: avatarnice/api-chat-x-prod-db
    DOCKER_IMAGE_TAG: ${CI_BUILD_TOKEN}
    DOCKER_CONTAINER_NAME: api-chat-x-container-prod-db
    POSTGRES_PASSWORD_PROD: ${POSTGRES_PASSWORD_PROD}
    POSTGRES_DB_PROD: ${POSTGRES_DB_PROD}
  before_script:
    -  docker login -u ${DOCKER_HUB_REGISTRY_USER} -p ${DOCKER_HUB_REGISTRY_PASSWORD}
  script:   
    - chmod u+x ./deploy/production-db/run.sh
    - ./deploy/production-db/run.sh

deploy production:
  stage: deploy production
  only:
    - master
  tags:
    - production
  variables:
    DOCKER_IMAGE_NAME: avatarnice/api-chat-x-prod
    DOCKER_IMAGE_TAG: ${CI_BUILD_TOKEN}
    DOCKER_CONTAINER_NAME: api-chat-x-container-prod
    RABBITMQ_USER_PROD: ${RABBITMQ_USER_PROD}
    RABBITMQ_PASSWORD_PROD: ${RABBITMQ_PASSWORD_PROD}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  before_script:
    -  docker login -u ${DOCKER_HUB_REGISTRY_USER} -p ${DOCKER_HUB_REGISTRY_PASSWORD}
  script:
    - chmod u+x ./deploy/production/build.sh
    - ./deploy/production/build.sh
    - docker push avatarnice/api-chat-x-prod:${CI_BUILD_TOKEN}
    - chmod u+x ./deploy/production/run.sh
    - ./deploy/production/run.sh
