version: '3'

services:
  postgres-server:
    image: "postgres:15"
    volumes: 
      - /home/chat-x-api/postgres:/data/postgres
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    command: [ "postgres", "-c", "wal_level=logical" ]
    deploy:
      placement:
          constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - chat-x_net
  postgres-server-master:
    image: "bitnami/postgresql"
    restart: always
    volumes: 
      - /home/chat-x-api/bitnami-postgres:/bitnami/postgresql
      - /home/chat-x-api/bitnami-postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
      - /home/chat-x-api/postgresql.conf:/bitnami/postgresql/conf/postgresql.conf
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_PROD}
    networks:
      - chat-x_net
  postgres-server-slave:
    image: "bitnami/postgresql"
    restart: always
    depends_on:
      - postgres-server-master
    volumes:
      - /home/chat-x-api/slave-postgresql.conf:/bitnami/postgresql/conf/postgresql.conf
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_HOST=postgres-server-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - chat-x_net
  postgres-server-slave-2:
    image: "bitnami/postgresql"
    restart: always
    depends_on:
      - postgres-server-master
    volumes:
      - /home/chat-x-api/slave-postgresql.conf:/bitnami/postgresql/conf/postgresql.conf
    ports:
      - "5435:5432"
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_HOST=postgres-server-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - chat-x_net
  postgres-server-slave-3:
    image: "bitnami/postgresql"
    restart: always
    depends_on:
      - postgres-server-master
    volumes:
      - /home/chat-x-api/slave-postgresql.conf:/bitnami/postgresql/conf/postgresql.conf
    ports:
      - "5436:5432"
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_HOST=postgres-server-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - chat-x_net
networks:
  chat-x_net:
    driver: overlay
